# Generated by Django 5.2.13 on 2026-04-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('mkv_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hls_path', models.CharField(blank=True, max_length=500, null=True)),
                ('production_year', models.IntegerField()),
                ('duration', models.IntegerField(help_text='minutes')),
                ('cover_image', models.URLField()),
                ('torrent_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('downloading', 'downloading'), ('processing', 'processing'), ('ready', 'ready'), ('error', 'error')], default='downloading', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('subtitle_link', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.movie')),
            ],
        ),
    ]
