# Generated by Django 5.2.13 on 2026-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_id_alter_subtitle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('downloading', 'downloading'), ('processing', 'processing'), ('ready', 'ready'), ('error', 'error')], default='pending', max_length=50),
        ),
    ]
