# Generated by Django 5.2.13 on 2026-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
