# Generated by Django 5.2.14 on 2026-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_last_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hls_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mkv_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
