# Generated by Django 5.2.14 on 2026-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_hls_path_remove_movie_mkv_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('streaming', 'Streaming'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
