# Generated by Django 5.2.14 on 2026-05-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hls_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
