# Generated by Django 5.2.14 on 2026-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='idle', max_length=20),
        ),
    ]
