# Generated by Django 5.2.14 on 2026-05-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='hls_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hls_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='idle', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrents', to='movies.movie')),
            ],
        ),
    ]
