# Generated by Django 5.2.14 on 2026-05-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_created_at_remove_movie_hls_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='torrent', to='movies.movie'),
        ),
    ]
