# Generated by Django 5.2.14 on 2026-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='starts',
            field=models.IntegerField(default=0),
        ),
    ]
