# Generated by Django 6.0.5 on 2026-05-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_movie_torrent_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('subtitle_link', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hls_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='idle', max_length=20)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='torrent', to='movies.movie')),
            ],
        ),
    ]
