import "./globals.css";
import type { Metadata } from "next";
import { poppins, inter, anton, bebasNeue } from "../lib/fonts";
import { Figtree } from "next/font/google";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/Footer";
import IntlProvider from "@/components/providers/IntlProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({subsets:['latin'],variable:'--font-sans', preload: false,});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn(poppins.variable, inter.variable, anton.variable, bebasNeue.variable, "font-sans", figtree.variable)}
    >
        <body className="min-h-screen bg-background" suppressHydrationWarning>
          <TooltipProvider>
            <IntlProvider>
              {children}
            </IntlProvider>
          </TooltipProvider>
          <div id="hover-root" />
          <Footer />
      </body>
    </html>
  );
}
