import type { Metadata } from "next";
import "./globals.css";
import { poppins, inter, anton } from "../lib/fonts";
import { Figtree } from "next/font/google";
import { cn } from "@/lib/utils";
import TopBar from "@/components/header/top-bar";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/footer";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans', preload: false,});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(poppins.variable, inter.variable, anton.variable, "font-sans", figtree.variable)}>
      <body className="min-h-screen bg-background overflow-x-hidden">
        <TopBar />
        <TooltipProvider>{children}</TooltipProvider>
        <div id="hover-root" />
        <Footer />
      </body>
    </html>
  );
}
