import "./globals.css";
import type { Metadata } from "next";
import { poppins, inter, anton, bebasNeue } from "../lib/fonts";
import { Figtree } from "next/font/google";
import { cn } from "@/lib/utils";
import TopBar from "@/components/header/top-bar";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/Footer";
// import { usePathname } from 'next/navigation';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({subsets:['latin'],variable:'--font-sans', preload: false,});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();

  return (
    <html
      lang="en"
      className={cn(poppins.variable, inter.variable, anton.variable, bebasNeue.variable, "font-sans", figtree.variable)}
    >
        <body className="min-h-screen bg-background">
        {
            <TopBar />
          // pathname !== '/landing' ? <TopBar /> :null
        }
        <TooltipProvider>{children}</TooltipProvider>
        <div id="hover-root" />
        <Footer />
      </body>
    </html>
  );
}
