# Generated by Django 6.0.5 on 2026-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='torrent_url',
            field=models.URLField(blank=True),
        ),
    ]
