# Generated by Django 5.2.9 on 2026-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoviestate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoviestate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
